services:
  captionmaker:
    image: ${DOCKER_REGISTRY-}captionmaker
    build:
      context: .
      dockerfile: CaptionMaker/Dockerfile
    ports:
      - 80:80
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - CAPTION_MAKER_DB_CONNECTION_STRING=Server=${DB_ADDRESS};Port=${DB_PORT};Database=caption-maker;Uid=${DB_USER};Pwd=${DB_PASSWORD};
      - CAPTION_MAKER_JWT_SECRET=${JWT_SECRET}
      - CAPTION_MAKER_IMAGE_STORAGE_URL=${IMAGE_STORAGE_URL}
      - CAPTION_MAKER_IMAGE_STORAGE_API_KEY=${IMAGE_STORAGE_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
  files:
    image: ${DOCKER_REGISTRY-}captionmaker-files
    build:
      context: .
      dockerfile: CaptionMaker.Files/Dockerfile
      args:
        - BASE_FILE_PATH=${BASE_FILE_PATH}
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - CAPTION_MAKER_FILES_BASE_FILE_PATH=${BASE_FILE_PATH}
      - CAPTION_MAKER_FILES_API_KEY=${IMAGE_STORAGE_API_KEY}
    volumes:
      - image-data:/usr/share/www/static
    networks:
       - backend
  mysql:
    image: mysql:lts
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=caption-maker
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "--password=$MYSQL_ROOT_PASSWORD", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:
  image-data:

networks:
  backend:
